### ISSUE TITLE
is project active?

### ISSUE THREAD

**Issue by mdsumner** [gdkrmr/zarr-R#16]
Hi is this project no longer active? Do you use an alternative?

Thank you 🙏

**Comment by gdkrmr** [comment]
no, the project is not active. libnetcdf should be able to read zarr files but this doesn't really work. You could either use python xarray via reticulate or YAXArrays.jl via JuliaCall.

**Comment by mdsumner** [comment]
thank you, would you mind saying why you gave up on it? fundamental problems or just not for you atm? I might take it on, but any guidance appreciated if you think it's a deadend or something

**Comment by gdkrmr** [comment]
There are a couple of reasons:
- Fairly complex project and my time is limited.
- The dependencies are nightmare, especially on windows. zarr requires blosc for compression and a ton of compression algorithms. This is no problem in Linux because you can just use system libraries but I have no Idea how to include them all under Windows.
- The dependencies throw compiler warnings and CRAN requires you to fix them.
- Also libnetcdf wanted to add Zarr support at the time so I didn't want to do any duplicated work.

Btw the json part worked pretty well and is well tested if I remember correctly. The headers have to be updated and and compiler warnings have to be fixed. With a bit of work it could be broken out and published on CRAN.

**Comment by gdkrmr** [comment]
Sorry, I missed the last part of  your comment ;-). If you want to take it on, I will be happy to collaborate. I think it is absolutely feasible to create a working package if someone puts enough work into it.

If you really want to do this, I would suggest that the first step is another search for Zarr libraries and a quick check how active development on z5 is.

**Comment by mdsumner** [comment]
Thanks so much, really appreciate the details - not sure I'm able in any timely fashion but there could be broader interest to leverage 😇🙏

**Comment by gdkrmr** [comment]
Yes, R really needs a working Zarr package :+1:
