### ISSUE TITLE
error when using blosc compression

### ISSUE THREAD

**Issue by gdkrmr** [gdkrmr/zarr-R#8]
@constantinpape I am getting this error when trying to write to a zarr array with `"blosc"` compression:

Blosc has not been compiled with '(null)' compression support.  Please use one having it.

I simply installed `libblosc-dev`, it is version 1.7.0. The error originates here:

https://github.com/Blosc/c-blosc/blob/7be242d2ddafddecd24067d82d71470210b2cd91/blosc/blosc.c#L695

Maybe this is related to constantinpape/z5#153?

**Comment by constantinpape** [comment]
I think this occurs because `blosc` gets passed the value `null` for the compressor.
Can you find out what values you are passing to the `compressionOptions` map?

So, this may indeed be related to https://github.com/constantinpape/z5/issues/153 if you are passing invalid values in there due to the confusing names.

**Comment by gdkrmr** [comment]
It works if I set the default compressor to `"lz4"` (constantinpape/z5#154).
